/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LegacyMilestoneEscrow } from './LegacyMilestoneEscrow.js';
export type { LegacyProjectRegistry } from './LegacyProjectRegistry.js';
export type { LegacyRoleManager } from './LegacyRoleManager.js';