/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace LegacyProjectRegistry {
      
    export type ProjectStruct = {id: BigNumberish, title: string, description: string, location: string, latitude: BigNumberish, longitude: BigNumberish, totalBudget: BigNumberish, spentAmount: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, officialAddress: AddressLike, contractorAddress: AddressLike, status: BigNumberish, milestoneCount: BigNumberish, category: BigNumberish}

    export type ProjectStructOutput = [id: bigint, title: string, description: string, location: string, latitude: bigint, longitude: bigint, totalBudget: bigint, spentAmount: bigint, startDate: bigint, endDate: bigint, officialAddress: string, contractorAddress: string, status: bigint, milestoneCount: bigint, category: bigint] & {id: bigint, title: string, description: string, location: string, latitude: bigint, longitude: bigint, totalBudget: bigint, spentAmount: bigint, startDate: bigint, endDate: bigint, officialAddress: string, contractorAddress: string, status: bigint, milestoneCount: bigint, category: bigint }
  
    }

  export interface LegacyProjectRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addSpentAmount" | "approveProject" | "assignContractor" | "closeProject" | "createProject" | "getAllProjectIds" | "getProject" | "incrementMilestoneCount" | "pauseProject" | "rejectProject" | "resumeProject" | "roleManager"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContractorAssigned" | "ProjectApproved" | "ProjectClosed" | "ProjectCreated" | "ProjectMilestoneCountUpdated" | "ProjectPaused" | "ProjectRejected" | "ProjectResumed" | "ProjectSpentUpdated" | "ProjectStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'addSpentAmount', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'assignContractor', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'closeProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [string, string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllProjectIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'incrementMilestoneCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectProject', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'resumeProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'roleManager', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addSpentAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignContractor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllProjectIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementMilestoneCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resumeProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roleManager', data: BytesLike): Result;
  }

  
    export namespace ContractorAssignedEvent {
      export type InputTuple = [projectId: BigNumberish, contractor: AddressLike];
      export type OutputTuple = [projectId: bigint, contractor: string];
      export interface OutputObject {projectId: bigint, contractor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectApprovedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike];
      export type OutputTuple = [projectId: bigint, auditor: string];
      export interface OutputObject {projectId: bigint, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectClosedEvent {
      export type InputTuple = [projectId: BigNumberish, official: AddressLike];
      export type OutputTuple = [projectId: bigint, official: string];
      export interface OutputObject {projectId: bigint, official: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, title: string, officialAddress: AddressLike, contractorAddress: AddressLike, totalBudget: BigNumberish];
      export type OutputTuple = [projectId: bigint, title: string, officialAddress: string, contractorAddress: string, totalBudget: bigint];
      export interface OutputObject {projectId: bigint, title: string, officialAddress: string, contractorAddress: string, totalBudget: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectMilestoneCountUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneCount: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneCount: bigint];
      export interface OutputObject {projectId: bigint, milestoneCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectPausedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike];
      export type OutputTuple = [projectId: bigint, auditor: string];
      export interface OutputObject {projectId: bigint, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectRejectedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike, reason: string];
      export type OutputTuple = [projectId: bigint, auditor: string, reason: string];
      export interface OutputObject {projectId: bigint, auditor: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectResumedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike];
      export type OutputTuple = [projectId: bigint, auditor: string];
      export interface OutputObject {projectId: bigint, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectSpentUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, spentAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, spentAmount: bigint];
      export interface OutputObject {projectId: bigint, spentAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectStatusUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [projectId: bigint, status: bigint];
      export interface OutputObject {projectId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LegacyProjectRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): LegacyProjectRegistry;
    waitForDeployment(): Promise<this>;

    interface: LegacyProjectRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addSpentAmount: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    assignContractor: TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    closeProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProject: TypedContractMethod<
      [title: string, description: string, location: string, latitude: BigNumberish, longitude: BigNumberish, budget: BigNumberish, endDate: BigNumberish, contractor: AddressLike, category: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getAllProjectIds: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [LegacyProjectRegistry.ProjectStructOutput],
      'view'
    >
    

    
    incrementMilestoneCount: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pauseProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectProject: TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    resumeProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    roleManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addSpentAmount'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assignContractor'): TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [title: string, description: string, location: string, latitude: BigNumberish, longitude: BigNumberish, budget: BigNumberish, endDate: BigNumberish, contractor: AddressLike, category: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllProjectIds'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [LegacyProjectRegistry.ProjectStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'incrementMilestoneCount'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectProject'): TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resumeProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'roleManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ContractorAssigned'): TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
getEvent(key: 'ProjectApproved'): TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
getEvent(key: 'ProjectClosed'): TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'ProjectMilestoneCountUpdated'): TypedContractEvent<ProjectMilestoneCountUpdatedEvent.InputTuple, ProjectMilestoneCountUpdatedEvent.OutputTuple, ProjectMilestoneCountUpdatedEvent.OutputObject>;
getEvent(key: 'ProjectPaused'): TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
getEvent(key: 'ProjectRejected'): TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
getEvent(key: 'ProjectResumed'): TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
getEvent(key: 'ProjectSpentUpdated'): TypedContractEvent<ProjectSpentUpdatedEvent.InputTuple, ProjectSpentUpdatedEvent.OutputTuple, ProjectSpentUpdatedEvent.OutputObject>;
getEvent(key: 'ProjectStatusUpdated'): TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'ContractorAssigned(uint256,address)': TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
      ContractorAssigned: TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
    

      'ProjectApproved(uint256,address)': TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
      ProjectApproved: TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
    

      'ProjectClosed(uint256,address)': TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
      ProjectClosed: TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
    

      'ProjectCreated(uint256,string,address,address,uint256)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'ProjectMilestoneCountUpdated(uint256,uint256)': TypedContractEvent<ProjectMilestoneCountUpdatedEvent.InputTuple, ProjectMilestoneCountUpdatedEvent.OutputTuple, ProjectMilestoneCountUpdatedEvent.OutputObject>;
      ProjectMilestoneCountUpdated: TypedContractEvent<ProjectMilestoneCountUpdatedEvent.InputTuple, ProjectMilestoneCountUpdatedEvent.OutputTuple, ProjectMilestoneCountUpdatedEvent.OutputObject>;
    

      'ProjectPaused(uint256,address)': TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
      ProjectPaused: TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
    

      'ProjectRejected(uint256,address,string)': TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
      ProjectRejected: TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
    

      'ProjectResumed(uint256,address)': TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
      ProjectResumed: TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
    

      'ProjectSpentUpdated(uint256,uint256)': TypedContractEvent<ProjectSpentUpdatedEvent.InputTuple, ProjectSpentUpdatedEvent.OutputTuple, ProjectSpentUpdatedEvent.OutputObject>;
      ProjectSpentUpdated: TypedContractEvent<ProjectSpentUpdatedEvent.InputTuple, ProjectSpentUpdatedEvent.OutputTuple, ProjectSpentUpdatedEvent.OutputObject>;
    

      'ProjectStatusUpdated(uint256,uint8)': TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;
      ProjectStatusUpdated: TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;
    
    };
  }