/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as importsSol from './Imports.sol/index.js';
export { NammaSevaMultisig__factory } from './NammaSevaMultisig__factory.js';