/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NammaSevaMultisig {
      
    export type TransactionStruct = {to: AddressLike, value: BigNumberish, executed: boolean, confirmations: BigNumberish, data: BytesLike}

    export type TransactionStructOutput = [to: string, value: bigint, executed: boolean, confirmations: bigint, data: string] & {to: string, value: bigint, executed: boolean, confirmations: bigint, data: string }
  
    }

  export interface NammaSevaMultisigInterface extends Interface {
    getFunction(nameOrSignature: "MAX_OWNERS" | "addOwner" | "changeThreshold" | "confirm" | "confirmedBy" | "execute" | "getOwners" | "getTransaction" | "isOwner" | "removeOwner" | "revoke" | "submit" | "threshold" | "transactionCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Confirmed" | "Deposit" | "Executed" | "OwnerAdded" | "OwnerRemoved" | "Revoked" | "Submitted" | "ThresholdChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_OWNERS', values?: undefined): string;
encodeFunctionData(functionFragment: 'addOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'changeThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirm', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmedBy', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'execute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOwners', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTransaction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revoke', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submit', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'threshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transactionCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_OWNERS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmedBy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'threshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactionCount', data: BytesLike): Result;
  }

  
    export namespace ConfirmedEvent {
      export type InputTuple = [txId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [txId: bigint, owner: string];
      export interface OutputObject {txId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutedEvent {
      export type InputTuple = [txId: BigNumberish];
      export type OutputTuple = [txId: bigint];
      export interface OutputObject {txId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerAddedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerRemovedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevokedEvent {
      export type InputTuple = [txId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [txId: bigint, owner: string];
      export interface OutputObject {txId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmittedEvent {
      export type InputTuple = [txId: BigNumberish, owner: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike];
      export type OutputTuple = [txId: bigint, owner: string, to: string, value: bigint, data: string];
      export interface OutputObject {txId: bigint, owner: string, to: string, value: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdChangedEvent {
      export type InputTuple = [threshold: BigNumberish];
      export type OutputTuple = [threshold: bigint];
      export interface OutputObject {threshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NammaSevaMultisig extends BaseContract {
    
    connect(runner?: ContractRunner | null): NammaSevaMultisig;
    waitForDeployment(): Promise<this>;

    interface: NammaSevaMultisigInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_OWNERS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    changeThreshold: TypedContractMethod<
      [threshold_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirm: TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmedBy: TypedContractMethod<
      [txId: BigNumberish, owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    execute: TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getOwners: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTransaction: TypedContractMethod<
      [txId: BigNumberish, ],
      [NammaSevaMultisig.TransactionStructOutput],
      'view'
    >
    

    
    isOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    removeOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revoke: TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submit: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    threshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transactionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_OWNERS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'changeThreshold'): TypedContractMethod<
      [threshold_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirm'): TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmedBy'): TypedContractMethod<
      [txId: BigNumberish, owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getOwners'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTransaction'): TypedContractMethod<
      [txId: BigNumberish, ],
      [NammaSevaMultisig.TransactionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [txId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submit'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'threshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transactionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Confirmed'): TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Executed'): TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
getEvent(key: 'OwnerAdded'): TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
getEvent(key: 'OwnerRemoved'): TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
getEvent(key: 'Revoked'): TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
getEvent(key: 'Submitted'): TypedContractEvent<SubmittedEvent.InputTuple, SubmittedEvent.OutputTuple, SubmittedEvent.OutputObject>;
getEvent(key: 'ThresholdChanged'): TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;

    filters: {
      
      'Confirmed(uint256,address)': TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
      Confirmed: TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
    

      'Deposit(address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Executed(uint256)': TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
      Executed: TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
    

      'OwnerAdded(address)': TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
      OwnerAdded: TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
    

      'OwnerRemoved(address)': TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
      OwnerRemoved: TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
    

      'Revoked(uint256,address)': TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
      Revoked: TypedContractEvent<RevokedEvent.InputTuple, RevokedEvent.OutputTuple, RevokedEvent.OutputObject>;
    

      'Submitted(uint256,address,address,uint256,bytes)': TypedContractEvent<SubmittedEvent.InputTuple, SubmittedEvent.OutputTuple, SubmittedEvent.OutputObject>;
      Submitted: TypedContractEvent<SubmittedEvent.InputTuple, SubmittedEvent.OutputTuple, SubmittedEvent.OutputObject>;
    

      'ThresholdChanged(uint8)': TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;
      ThresholdChanged: TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;
    
    };
  }