/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { RejectingReceiver, RejectingReceiverInterface } from "../../mocks/RejectingReceiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "call",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x60808060405234610016576101e5908161001b8239f35b5f80fdfe6080604052600436101561001d575b3615610018575f80fd5b61017e565b5f3560e01c631b8b921d0361000e57346100a75760403660031901126100a7576004356001600160a01b03811681036100a75760243567ffffffffffffffff8082116100a757366023830112156100a75781600401359081116100a75736602482840101116100a7576100a3926024610097930190610106565b604051918291826100ab565b0390f35b5f80fd5b602080825282518183018190529093925f5b8281106100de57505060409293505f838284010152601f8019910116010190565b8181018601518482016040015285016100bd565b634e487b7160e01b5f52604160045260245ffd5b5f92838093826040519384928337810182815203925af13d156101765767ffffffffffffffff903d8281116101715760405192601f8201601f19908116603f01168401908111848210176101715760405282523d5f602084013e5b156101695790565b602081519101fd5b6100f2565b606090610161565b60405162461bcd60e51b81526020600482015260096024820152686e6f207468616e6b7360b81b6044820152606490fdfea2646970667358221220c1979767e8735b908c6438369ff2eb5fc7a98d7cbea8711a034d5081a94e30fb64736f6c63430008180033";

  
      type RejectingReceiverConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: RejectingReceiverConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class RejectingReceiver__factory extends ContractFactory {
    
      constructor(...args: RejectingReceiverConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<RejectingReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): RejectingReceiver__factory {
      return super.connect(runner) as RejectingReceiver__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): RejectingReceiverInterface {
      return new Interface(_abi) as RejectingReceiverInterface;
    }
    
    override attach(address: string | Addressable): RejectingReceiver {
      return super.attach(address) as RejectingReceiver;
    }
  static connect(address: string, runner?: ContractRunner | null): RejectingReceiver {
      return new Contract(address, _abi, runner) as unknown as RejectingReceiver;
    }
  }

  
  