// Generated by packages/contracts/scripts/exportAbis.ts — do not edit.

export type ContractName = "NammaSevaAccess" | "ProjectRegistry" | "MilestoneEscrow" | "GrievanceRegistry" | "TenderRegistry" | "TrustedForwarder" | "NammaSevaMultisig" | "NammaSevaTimelock";

export type Deployment = {
  network: string;
  chainId: number;
  /** First block to index (block before the first deploy tx). */
  blockNumber: number;
  commit: string;
  deployedAt: string;
  deployer: string;
  mode: "LEDGER" | "ESCROW";
  contracts: Partial<Record<ContractName, { address: `0x${string}`; implementation?: `0x${string}` }>>;
};

export const DEPLOYMENTS: Record<string, Deployment> = {};

/** Deployment manifest for a network name, or undefined if not deployed there. */
export function getDeployment(network: string): Deployment | undefined {
  return DEPLOYMENTS[network];
}

/** Address of `name` on `network`; throws if missing so misconfiguration fails loudly at boot. */
export function contractAddress(network: string, name: ContractName): `0x${string}` {
  const address = DEPLOYMENTS[network]?.contracts[name]?.address;
  if (!address) throw new Error(`${name} is not deployed on "${network}"`);
  return address;
}
