/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governance from './governance/index.js';
export * as interfaces from './interfaces/index.js';
export * as legacy from './legacy/index.js';
export * as mocks from './mocks/index.js';
export { GrievanceRegistry__factory } from './GrievanceRegistry__factory.js';
export { MilestoneEscrow__factory } from './MilestoneEscrow__factory.js';
export { NammaSevaAccess__factory } from './NammaSevaAccess__factory.js';
export { NammaSevaBase__factory } from './NammaSevaBase__factory.js';
export { ProjectRegistry__factory } from './ProjectRegistry__factory.js';
export { TenderRegistry__factory } from './TenderRegistry__factory.js';