// Generated by packages/contracts/scripts/exportAbis.ts — do not edit.
export const grievanceRegistryAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "trustedForwarder_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "AddressEmptyCode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadySet",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "name": "AlreadyUpvoted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CitizenMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "DailyLimitReached",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "ERC1967InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC1967NonPayable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FailedCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "name": "GrievanceNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAction",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCitizen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidContent",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "internalType": "enum GrievanceRegistry.Status",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "InvalidGrievanceStatus",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitialization",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSettings",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "NotACitizen",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint32",
        "name": "wardId",
        "type": "uint32"
      }
    ],
    "name": "NotInWard",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInitializing",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "name": "OwnGrievance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "internalType": "enum IProjectRegistry.Status",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "ProjectClosedForGrievances",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SystemPaused",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UUPSUnauthorizedCallContext",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "slot",
        "type": "bytes32"
      }
    ],
    "name": "UUPSUnsupportedProxiableUUID",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      }
    ],
    "name": "Unauthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "CitizenSignerSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "enum GrievanceRegistry.Category",
        "name": "category",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "cid",
        "type": "string"
      }
    ],
    "name": "GrievanceFiled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "auditor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum GrievanceRegistry.Action",
        "name": "action",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "responseCID",
        "type": "string"
      }
    ],
    "name": "GrievanceResponded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "upvotes",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "respondBy",
        "type": "uint64"
      }
    ],
    "name": "GrievanceThresholdReached",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "upvotes",
        "type": "uint32"
      }
    ],
    "name": "GrievanceUpvoted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "Initialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "escalationThreshold",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "maxGrievancesPerDay",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "responseSla",
        "type": "uint64"
      }
    ],
    "name": "SettingsUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "Upgraded",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "UPGRADE_INTERFACE_VERSION",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "access",
    "outputs": [
      {
        "internalType": "contract NammaSevaAccess",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "citizenOfSigner",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "escalationThreshold",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "internalType": "enum GrievanceRegistry.Category",
        "name": "category",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "cid",
        "type": "string"
      },
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "fileGrievance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "day",
        "type": "uint256"
      }
    ],
    "name": "filedOnDay",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "name": "getGrievance",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "citizenHash",
            "type": "bytes32"
          },
          {
            "internalType": "uint64",
            "name": "id",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "projectId",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "createdAt",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "upvotes",
            "type": "uint32"
          },
          {
            "internalType": "enum GrievanceRegistry.Category",
            "name": "category",
            "type": "uint8"
          },
          {
            "internalType": "enum GrievanceRegistry.Status",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "enum GrievanceRegistry.Action",
            "name": "action",
            "type": "uint8"
          },
          {
            "internalType": "uint64",
            "name": "escalatedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "respondedAt",
            "type": "uint64"
          }
        ],
        "internalType": "struct GrievanceRegistry.Grievance",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "grievanceCount",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "hasUpvoted",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "access_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "registry_",
        "type": "address"
      },
      {
        "internalType": "uint32",
        "name": "escalationThreshold_",
        "type": "uint32"
      },
      {
        "internalType": "uint8",
        "name": "maxGrievancesPerDay_",
        "type": "uint8"
      },
      {
        "internalType": "uint64",
        "name": "responseSla_",
        "type": "uint64"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      }
    ],
    "name": "isOverdue",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "forwarder",
        "type": "address"
      }
    ],
    "name": "isTrustedForwarder",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxGrievancesPerDay",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "proxiableUUID",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "registry",
    "outputs": [
      {
        "internalType": "contract IProjectRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "responseCID",
        "type": "string"
      },
      {
        "internalType": "enum GrievanceRegistry.Action",
        "name": "action",
        "type": "uint8"
      }
    ],
    "name": "respond",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "responseSla",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "setCitizenSigner",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "escalationThreshold_",
        "type": "uint32"
      },
      {
        "internalType": "uint8",
        "name": "maxGrievancesPerDay_",
        "type": "uint8"
      },
      {
        "internalType": "uint64",
        "name": "responseSla_",
        "type": "uint64"
      }
    ],
    "name": "setSettings",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "trustedForwarder",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newImplementation",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "upgradeToAndCall",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "grievanceId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "citizenHash",
        "type": "bytes32"
      }
    ],
    "name": "upvote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
