/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IProjectRegistry {
      
    export type ProjectStruct = {metaHash: BytesLike, budget: BigNumberish, spent: BigNumberish, id: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, wardId: BigNumberish, departmentId: BigNumberish, latE6: BigNumberish, lngE6: BigNumberish, official: AddressLike, contractor: AddressLike, status: BigNumberish, category: BigNumberish, approvalThreshold: BigNumberish, approvalCount: BigNumberish, milestoneCount: BigNumberish, cancelRequested: boolean}

    export type ProjectStructOutput = [metaHash: string, budget: bigint, spent: bigint, id: bigint, startDate: bigint, endDate: bigint, wardId: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, official: string, contractor: string, status: bigint, category: bigint, approvalThreshold: bigint, approvalCount: bigint, milestoneCount: bigint, cancelRequested: boolean] & {metaHash: string, budget: bigint, spent: bigint, id: bigint, startDate: bigint, endDate: bigint, wardId: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, official: string, contractor: string, status: bigint, category: bigint, approvalThreshold: bigint, approvalCount: bigint, milestoneCount: bigint, cancelRequested: boolean }
  
    }

  export interface IProjectRegistryInterface extends Interface {
    getFunction(nameOrSignature: "assignContractor" | "getProject" | "pauseByGrievance" | "recordMilestoneCreated" | "recordSpent"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'assignContractor', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseByGrievance', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordMilestoneCreated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordSpent', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'assignContractor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseByGrievance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMilestoneCreated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordSpent', data: BytesLike): Result;
  }

  

  export interface IProjectRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IProjectRegistry;
    waitForDeployment(): Promise<this>;

    interface: IProjectRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    assignContractor: TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [IProjectRegistry.ProjectStructOutput],
      'view'
    >
    

    
    pauseByGrievance: TypedContractMethod<
      [projectId: BigNumberish, grievanceId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordMilestoneCreated: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordSpent: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'assignContractor'): TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [IProjectRegistry.ProjectStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'pauseByGrievance'): TypedContractMethod<
      [projectId: BigNumberish, grievanceId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordMilestoneCreated'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordSpent'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }