/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace GrievanceRegistry {
      
    export type GrievanceStruct = {citizenHash: BytesLike, id: BigNumberish, projectId: BigNumberish, createdAt: BigNumberish, upvotes: BigNumberish, category: BigNumberish, status: BigNumberish, action: BigNumberish, escalatedAt: BigNumberish, respondedAt: BigNumberish}

    export type GrievanceStructOutput = [citizenHash: string, id: bigint, projectId: bigint, createdAt: bigint, upvotes: bigint, category: bigint, status: bigint, action: bigint, escalatedAt: bigint, respondedAt: bigint] & {citizenHash: string, id: bigint, projectId: bigint, createdAt: bigint, upvotes: bigint, category: bigint, status: bigint, action: bigint, escalatedAt: bigint, respondedAt: bigint }
  
    }

  export interface GrievanceRegistryInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "access" | "citizenOfSigner" | "escalationThreshold" | "fileGrievance" | "filedOnDay" | "getGrievance" | "grievanceCount" | "hasUpvoted" | "initialize" | "isOverdue" | "isTrustedForwarder" | "maxGrievancesPerDay" | "proxiableUUID" | "registry" | "respond" | "responseSla" | "setCitizenSigner" | "setSettings" | "trustedForwarder" | "upgradeToAndCall" | "upvote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CitizenSignerSet" | "GrievanceFiled" | "GrievanceResponded" | "GrievanceThresholdReached" | "GrievanceUpvoted" | "Initialized" | "SettingsUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'access', values?: undefined): string;
encodeFunctionData(functionFragment: 'citizenOfSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'escalationThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'fileGrievance', values: [BigNumberish, BigNumberish, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'filedOnDay', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGrievance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grievanceCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasUpvoted', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOverdue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isTrustedForwarder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxGrievancesPerDay', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'respond', values: [BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'responseSla', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCitizenSigner', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setSettings', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'trustedForwarder', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'upvote', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'access', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'citizenOfSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escalationThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fileGrievance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'filedOnDay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGrievance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grievanceCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasUpvoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOverdue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTrustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxGrievancesPerDay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'respond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'responseSla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCitizenSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upvote', data: BytesLike): Result;
  }

  
    export namespace CitizenSignerSetEvent {
      export type InputTuple = [signer: AddressLike, citizenHash: BytesLike];
      export type OutputTuple = [signer: string, citizenHash: string];
      export interface OutputObject {signer: string, citizenHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GrievanceFiledEvent {
      export type InputTuple = [grievanceId: BigNumberish, projectId: BigNumberish, citizenHash: BytesLike, category: BigNumberish, cid: string];
      export type OutputTuple = [grievanceId: bigint, projectId: bigint, citizenHash: string, category: bigint, cid: string];
      export interface OutputObject {grievanceId: bigint, projectId: bigint, citizenHash: string, category: bigint, cid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GrievanceRespondedEvent {
      export type InputTuple = [grievanceId: BigNumberish, projectId: BigNumberish, auditor: AddressLike, action: BigNumberish, responseCID: string];
      export type OutputTuple = [grievanceId: bigint, projectId: bigint, auditor: string, action: bigint, responseCID: string];
      export interface OutputObject {grievanceId: bigint, projectId: bigint, auditor: string, action: bigint, responseCID: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GrievanceThresholdReachedEvent {
      export type InputTuple = [grievanceId: BigNumberish, projectId: BigNumberish, upvotes: BigNumberish, respondBy: BigNumberish];
      export type OutputTuple = [grievanceId: bigint, projectId: bigint, upvotes: bigint, respondBy: bigint];
      export interface OutputObject {grievanceId: bigint, projectId: bigint, upvotes: bigint, respondBy: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GrievanceUpvotedEvent {
      export type InputTuple = [grievanceId: BigNumberish, projectId: BigNumberish, citizenHash: BytesLike, upvotes: BigNumberish];
      export type OutputTuple = [grievanceId: bigint, projectId: bigint, citizenHash: string, upvotes: bigint];
      export interface OutputObject {grievanceId: bigint, projectId: bigint, citizenHash: string, upvotes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettingsUpdatedEvent {
      export type InputTuple = [escalationThreshold: BigNumberish, maxGrievancesPerDay: BigNumberish, responseSla: BigNumberish];
      export type OutputTuple = [escalationThreshold: bigint, maxGrievancesPerDay: bigint, responseSla: bigint];
      export interface OutputObject {escalationThreshold: bigint, maxGrievancesPerDay: bigint, responseSla: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GrievanceRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): GrievanceRegistry;
    waitForDeployment(): Promise<this>;

    interface: GrievanceRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    access: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    citizenOfSigner: TypedContractMethod<
      [signer: AddressLike, ],
      [string],
      'view'
    >
    

    
    escalationThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fileGrievance: TypedContractMethod<
      [projectId: BigNumberish, category: BigNumberish, cid: string, citizenHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    filedOnDay: TypedContractMethod<
      [citizenHash: BytesLike, day: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getGrievance: TypedContractMethod<
      [grievanceId: BigNumberish, ],
      [GrievanceRegistry.GrievanceStructOutput],
      'view'
    >
    

    
    grievanceCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasUpvoted: TypedContractMethod<
      [grievanceId: BigNumberish, citizenHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, escalationThreshold_: BigNumberish, maxGrievancesPerDay_: BigNumberish, responseSla_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isOverdue: TypedContractMethod<
      [grievanceId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isTrustedForwarder: TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxGrievancesPerDay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    respond: TypedContractMethod<
      [grievanceId: BigNumberish, responseCID: string, action: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    responseSla: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setCitizenSigner: TypedContractMethod<
      [signer: AddressLike, citizenHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setSettings: TypedContractMethod<
      [escalationThreshold_: BigNumberish, maxGrievancesPerDay_: BigNumberish, responseSla_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    trustedForwarder: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    upvote: TypedContractMethod<
      [grievanceId: BigNumberish, citizenHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'access'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'citizenOfSigner'): TypedContractMethod<
      [signer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'escalationThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fileGrievance'): TypedContractMethod<
      [projectId: BigNumberish, category: BigNumberish, cid: string, citizenHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'filedOnDay'): TypedContractMethod<
      [citizenHash: BytesLike, day: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getGrievance'): TypedContractMethod<
      [grievanceId: BigNumberish, ],
      [GrievanceRegistry.GrievanceStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grievanceCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasUpvoted'): TypedContractMethod<
      [grievanceId: BigNumberish, citizenHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, escalationThreshold_: BigNumberish, maxGrievancesPerDay_: BigNumberish, responseSla_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isOverdue'): TypedContractMethod<
      [grievanceId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isTrustedForwarder'): TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxGrievancesPerDay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'respond'): TypedContractMethod<
      [grievanceId: BigNumberish, responseCID: string, action: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'responseSla'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setCitizenSigner'): TypedContractMethod<
      [signer: AddressLike, citizenHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSettings'): TypedContractMethod<
      [escalationThreshold_: BigNumberish, maxGrievancesPerDay_: BigNumberish, responseSla_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trustedForwarder'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'upvote'): TypedContractMethod<
      [grievanceId: BigNumberish, citizenHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CitizenSignerSet'): TypedContractEvent<CitizenSignerSetEvent.InputTuple, CitizenSignerSetEvent.OutputTuple, CitizenSignerSetEvent.OutputObject>;
getEvent(key: 'GrievanceFiled'): TypedContractEvent<GrievanceFiledEvent.InputTuple, GrievanceFiledEvent.OutputTuple, GrievanceFiledEvent.OutputObject>;
getEvent(key: 'GrievanceResponded'): TypedContractEvent<GrievanceRespondedEvent.InputTuple, GrievanceRespondedEvent.OutputTuple, GrievanceRespondedEvent.OutputObject>;
getEvent(key: 'GrievanceThresholdReached'): TypedContractEvent<GrievanceThresholdReachedEvent.InputTuple, GrievanceThresholdReachedEvent.OutputTuple, GrievanceThresholdReachedEvent.OutputObject>;
getEvent(key: 'GrievanceUpvoted'): TypedContractEvent<GrievanceUpvotedEvent.InputTuple, GrievanceUpvotedEvent.OutputTuple, GrievanceUpvotedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'SettingsUpdated'): TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'CitizenSignerSet(address,bytes32)': TypedContractEvent<CitizenSignerSetEvent.InputTuple, CitizenSignerSetEvent.OutputTuple, CitizenSignerSetEvent.OutputObject>;
      CitizenSignerSet: TypedContractEvent<CitizenSignerSetEvent.InputTuple, CitizenSignerSetEvent.OutputTuple, CitizenSignerSetEvent.OutputObject>;
    

      'GrievanceFiled(uint256,uint256,bytes32,uint8,string)': TypedContractEvent<GrievanceFiledEvent.InputTuple, GrievanceFiledEvent.OutputTuple, GrievanceFiledEvent.OutputObject>;
      GrievanceFiled: TypedContractEvent<GrievanceFiledEvent.InputTuple, GrievanceFiledEvent.OutputTuple, GrievanceFiledEvent.OutputObject>;
    

      'GrievanceResponded(uint256,uint256,address,uint8,string)': TypedContractEvent<GrievanceRespondedEvent.InputTuple, GrievanceRespondedEvent.OutputTuple, GrievanceRespondedEvent.OutputObject>;
      GrievanceResponded: TypedContractEvent<GrievanceRespondedEvent.InputTuple, GrievanceRespondedEvent.OutputTuple, GrievanceRespondedEvent.OutputObject>;
    

      'GrievanceThresholdReached(uint256,uint256,uint32,uint64)': TypedContractEvent<GrievanceThresholdReachedEvent.InputTuple, GrievanceThresholdReachedEvent.OutputTuple, GrievanceThresholdReachedEvent.OutputObject>;
      GrievanceThresholdReached: TypedContractEvent<GrievanceThresholdReachedEvent.InputTuple, GrievanceThresholdReachedEvent.OutputTuple, GrievanceThresholdReachedEvent.OutputObject>;
    

      'GrievanceUpvoted(uint256,uint256,bytes32,uint32)': TypedContractEvent<GrievanceUpvotedEvent.InputTuple, GrievanceUpvotedEvent.OutputTuple, GrievanceUpvotedEvent.OutputObject>;
      GrievanceUpvoted: TypedContractEvent<GrievanceUpvotedEvent.InputTuple, GrievanceUpvotedEvent.OutputTuple, GrievanceUpvotedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'SettingsUpdated(uint32,uint8,uint64)': TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
      SettingsUpdated: TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }