/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MilestoneEscrow {
      
    export type MilestoneStruct = {metaHash: BytesLike, proofHash: BytesLike, amount: BigNumberish, id: BigNumberish, projectId: BigNumberish, proofLatE6: BigNumberish, proofLngE6: BigNumberish, submittedAt: BigNumberish, round: BigNumberish, approvalCount: BigNumberish, status: BigNumberish}

    export type MilestoneStructOutput = [metaHash: string, proofHash: string, amount: bigint, id: bigint, projectId: bigint, proofLatE6: bigint, proofLngE6: bigint, submittedAt: bigint, round: bigint, approvalCount: bigint, status: bigint] & {metaHash: string, proofHash: string, amount: bigint, id: bigint, projectId: bigint, proofLatE6: bigint, proofLngE6: bigint, submittedAt: bigint, round: bigint, approvalCount: bigint, status: bigint }
  
    }

  export interface MilestoneEscrowInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "access" | "approveMilestone" | "cancelMilestone" | "createMilestone" | "fundProject" | "funds" | "getMilestone" | "hasApproved" | "initialize" | "milestoneCount" | "mode" | "proxiableUUID" | "recordSanction" | "refundUnallocated" | "registry" | "rejectMilestone" | "releaseFunds" | "submitProof" | "treasury" | "unsettledMilestones" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FundsReleased" | "Initialized" | "MilestoneApproved" | "MilestoneCreated" | "MilestoneRejected" | "MilestoneStatusChanged" | "MilestoneVoided" | "ProjectFunded" | "ProofSubmitted" | "UnallocatedRefunded" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'access', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelMilestone', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createMilestone', values: [BigNumberish, BytesLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'funds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasApproved', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'milestoneCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'mode', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordSanction', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'refundUnallocated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectMilestone', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseFunds', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'submitProof', values: [BigNumberish, string, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unsettledMilestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'access', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'funds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestoneCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordSanction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundUnallocated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unsettledMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace FundsReleasedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, contractor: AddressLike, amount: BigNumberish, paymentRefHash: BytesLike];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, contractor: string, amount: bigint, paymentRefHash: string];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, contractor: string, amount: bigint, paymentRefHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, auditor: AddressLike, approvalCount: BigNumberish, round: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, auditor: string, approvalCount: bigint, round: bigint];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, auditor: string, approvalCount: bigint, round: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneCreatedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, metaHash: BytesLike, metaCID: string, amount: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, metaHash: string, metaCID: string, amount: bigint];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, metaHash: string, metaCID: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRejectedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, auditor: AddressLike, reasonHash: BytesLike, round: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, auditor: string, reasonHash: string, round: bigint];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, auditor: string, reasonHash: string, round: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneStatusChangedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, status: bigint];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneVoidedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, reasonHash: BytesLike];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, reasonHash: string];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectFundedEvent {
      export type InputTuple = [projectId: BigNumberish, official: AddressLike, amount: BigNumberish, sanctionRefHash: BytesLike, balance: BigNumberish];
      export type OutputTuple = [projectId: bigint, official: string, amount: bigint, sanctionRefHash: string, balance: bigint];
      export interface OutputObject {projectId: bigint, official: string, amount: bigint, sanctionRefHash: string, balance: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofSubmittedEvent {
      export type InputTuple = [milestoneId: BigNumberish, projectId: BigNumberish, contractor: AddressLike, proofCID: string, proofHash: BytesLike, latE6: BigNumberish, lngE6: BigNumberish, round: BigNumberish];
      export type OutputTuple = [milestoneId: bigint, projectId: bigint, contractor: string, proofCID: string, proofHash: string, latE6: bigint, lngE6: bigint, round: bigint];
      export interface OutputObject {milestoneId: bigint, projectId: bigint, contractor: string, proofCID: string, proofHash: string, latE6: bigint, lngE6: bigint, round: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnallocatedRefundedEvent {
      export type InputTuple = [projectId: BigNumberish, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, to: string, amount: bigint];
      export interface OutputObject {projectId: bigint, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MilestoneEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): MilestoneEscrow;
    waitForDeployment(): Promise<this>;

    interface: MilestoneEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    access: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveMilestone: TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelMilestone: TypedContractMethod<
      [milestoneId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createMilestone: TypedContractMethod<
      [projectId: BigNumberish, metaHash: BytesLike, metaCID: string, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    fundProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    funds: TypedContractMethod<
      [projectId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {funded: bigint, balance: bigint, allocated: bigint, unsettled: bigint }],
      'view'
    >
    

    
    getMilestone: TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [MilestoneEscrow.MilestoneStructOutput],
      'view'
    >
    

    
    hasApproved: TypedContractMethod<
      [milestoneId: BigNumberish, auditor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, mode_: BigNumberish, treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    milestoneCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mode: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordSanction: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, sanctionRefHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    refundUnallocated: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rejectMilestone: TypedContractMethod<
      [milestoneId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [milestoneId: BigNumberish, paymentRefHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitProof: TypedContractMethod<
      [milestoneId: BigNumberish, proofCID: string, proofHash: BytesLike, latE6: BigNumberish, lngE6: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unsettledMilestones: TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'access'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelMilestone'): TypedContractMethod<
      [milestoneId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMilestone'): TypedContractMethod<
      [projectId: BigNumberish, metaHash: BytesLike, metaCID: string, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'funds'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {funded: bigint, balance: bigint, allocated: bigint, unsettled: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestone'): TypedContractMethod<
      [milestoneId: BigNumberish, ],
      [MilestoneEscrow.MilestoneStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasApproved'): TypedContractMethod<
      [milestoneId: BigNumberish, auditor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, mode_: BigNumberish, treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'milestoneCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mode'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordSanction'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, sanctionRefHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundUnallocated'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rejectMilestone'): TypedContractMethod<
      [milestoneId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [milestoneId: BigNumberish, paymentRefHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitProof'): TypedContractMethod<
      [milestoneId: BigNumberish, proofCID: string, proofHash: BytesLike, latE6: BigNumberish, lngE6: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unsettledMilestones'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneCreated'): TypedContractEvent<MilestoneCreatedEvent.InputTuple, MilestoneCreatedEvent.OutputTuple, MilestoneCreatedEvent.OutputObject>;
getEvent(key: 'MilestoneRejected'): TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
getEvent(key: 'MilestoneStatusChanged'): TypedContractEvent<MilestoneStatusChangedEvent.InputTuple, MilestoneStatusChangedEvent.OutputTuple, MilestoneStatusChangedEvent.OutputObject>;
getEvent(key: 'MilestoneVoided'): TypedContractEvent<MilestoneVoidedEvent.InputTuple, MilestoneVoidedEvent.OutputTuple, MilestoneVoidedEvent.OutputObject>;
getEvent(key: 'ProjectFunded'): TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;
getEvent(key: 'ProofSubmitted'): TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
getEvent(key: 'UnallocatedRefunded'): TypedContractEvent<UnallocatedRefundedEvent.InputTuple, UnallocatedRefundedEvent.OutputTuple, UnallocatedRefundedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'FundsReleased(uint256,uint256,address,uint256,bytes32)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256,address,uint8,uint32)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneCreated(uint256,uint256,bytes32,string,uint256)': TypedContractEvent<MilestoneCreatedEvent.InputTuple, MilestoneCreatedEvent.OutputTuple, MilestoneCreatedEvent.OutputObject>;
      MilestoneCreated: TypedContractEvent<MilestoneCreatedEvent.InputTuple, MilestoneCreatedEvent.OutputTuple, MilestoneCreatedEvent.OutputObject>;
    

      'MilestoneRejected(uint256,uint256,address,bytes32,uint32)': TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
      MilestoneRejected: TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
    

      'MilestoneStatusChanged(uint256,uint256,uint8)': TypedContractEvent<MilestoneStatusChangedEvent.InputTuple, MilestoneStatusChangedEvent.OutputTuple, MilestoneStatusChangedEvent.OutputObject>;
      MilestoneStatusChanged: TypedContractEvent<MilestoneStatusChangedEvent.InputTuple, MilestoneStatusChangedEvent.OutputTuple, MilestoneStatusChangedEvent.OutputObject>;
    

      'MilestoneVoided(uint256,uint256,bytes32)': TypedContractEvent<MilestoneVoidedEvent.InputTuple, MilestoneVoidedEvent.OutputTuple, MilestoneVoidedEvent.OutputObject>;
      MilestoneVoided: TypedContractEvent<MilestoneVoidedEvent.InputTuple, MilestoneVoidedEvent.OutputTuple, MilestoneVoidedEvent.OutputObject>;
    

      'ProjectFunded(uint256,address,uint256,bytes32,uint256)': TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;
      ProjectFunded: TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;
    

      'ProofSubmitted(uint256,uint256,address,string,bytes32,int32,int32,uint32)': TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
      ProofSubmitted: TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
    

      'UnallocatedRefunded(uint256,address,uint256)': TypedContractEvent<UnallocatedRefundedEvent.InputTuple, UnallocatedRefundedEvent.OutputTuple, UnallocatedRefundedEvent.OutputObject>;
      UnallocatedRefunded: TypedContractEvent<UnallocatedRefundedEvent.InputTuple, UnallocatedRefundedEvent.OutputTuple, UnallocatedRefundedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }