/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProjectRegistry {
      
    export type NewProjectStruct = {metaHash: BytesLike, metaCID: string, wardId: BigNumberish, departmentId: BigNumberish, category: BigNumberish, latE6: BigNumberish, lngE6: BigNumberish, budget: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, contractor: AddressLike, approvalThreshold: BigNumberish}

    export type NewProjectStructOutput = [metaHash: string, metaCID: string, wardId: bigint, departmentId: bigint, category: bigint, latE6: bigint, lngE6: bigint, budget: bigint, startDate: bigint, endDate: bigint, contractor: string, approvalThreshold: bigint] & {metaHash: string, metaCID: string, wardId: bigint, departmentId: bigint, category: bigint, latE6: bigint, lngE6: bigint, budget: bigint, startDate: bigint, endDate: bigint, contractor: string, approvalThreshold: bigint }
  
    }

export declare namespace IProjectRegistry {
      
    export type ProjectStruct = {metaHash: BytesLike, budget: BigNumberish, spent: BigNumberish, id: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, wardId: BigNumberish, departmentId: BigNumberish, latE6: BigNumberish, lngE6: BigNumberish, official: AddressLike, contractor: AddressLike, status: BigNumberish, category: BigNumberish, approvalThreshold: BigNumberish, approvalCount: BigNumberish, milestoneCount: BigNumberish, cancelRequested: boolean}

    export type ProjectStructOutput = [metaHash: string, budget: bigint, spent: bigint, id: bigint, startDate: bigint, endDate: bigint, wardId: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, official: string, contractor: string, status: bigint, category: bigint, approvalThreshold: bigint, approvalCount: bigint, milestoneCount: bigint, cancelRequested: boolean] & {metaHash: string, budget: bigint, spent: bigint, id: bigint, startDate: bigint, endDate: bigint, wardId: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, official: string, contractor: string, status: bigint, category: bigint, approvalThreshold: bigint, approvalCount: bigint, milestoneCount: bigint, cancelRequested: boolean }
  
    }

  export interface ProjectRegistryInterface extends Interface {
    getFunction(nameOrSignature: "MAX_APPROVAL_THRESHOLD" | "UPGRADE_INTERFACE_VERSION" | "access" | "approveProject" | "assignContractor" | "closeProject" | "confirmCancel" | "createProject" | "escrow" | "exists" | "getProject" | "grievanceRegistry" | "hasApprovedProject" | "initialize" | "pauseByGrievance" | "pauseProject" | "projectCount" | "proxiableUUID" | "recordMilestoneCreated" | "recordSpent" | "rejectProject" | "requestCancel" | "resumeProject" | "setEscrow" | "setGrievanceRegistry" | "setTenderRegistry" | "tenderRegistry" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContractorAssigned" | "Initialized" | "LinkedContractSet" | "MilestoneCountUpdated" | "ProjectApproved" | "ProjectCancelRequested" | "ProjectCancelled" | "ProjectClosed" | "ProjectCreated" | "ProjectPaused" | "ProjectRejected" | "ProjectResumed" | "ProjectStatusChanged" | "SpentUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_APPROVAL_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'access', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'assignContractor', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'closeProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmCancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [ProjectRegistry.NewProjectStruct]): string;
encodeFunctionData(functionFragment: 'escrow', values?: undefined): string;
encodeFunctionData(functionFragment: 'exists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grievanceRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasApprovedProject', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'pauseByGrievance', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseProject', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'projectCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordMilestoneCreated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordSpent', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectProject', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'requestCancel', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'resumeProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setEscrow', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setGrievanceRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTenderRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tenderRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_APPROVAL_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'access', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignContractor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmCancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grievanceRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApprovedProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseByGrievance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordMilestoneCreated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordSpent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestCancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resumeProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGrievanceRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTenderRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenderRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace ContractorAssignedEvent {
      export type InputTuple = [projectId: BigNumberish, contractor: AddressLike, assignedBy: AddressLike];
      export type OutputTuple = [projectId: bigint, contractor: string, assignedBy: string];
      export interface OutputObject {projectId: bigint, contractor: string, assignedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LinkedContractSetEvent {
      export type InputTuple = [kind: BytesLike, target: AddressLike];
      export type OutputTuple = [kind: string, target: string];
      export interface OutputObject {kind: string, target: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneCountUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneCount: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneCount: bigint];
      export interface OutputObject {projectId: bigint, milestoneCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectApprovedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike, approvalCount: BigNumberish];
      export type OutputTuple = [projectId: bigint, auditor: string, approvalCount: bigint];
      export interface OutputObject {projectId: bigint, auditor: string, approvalCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCancelRequestedEvent {
      export type InputTuple = [projectId: BigNumberish, official: AddressLike, reasonHash: BytesLike];
      export type OutputTuple = [projectId: bigint, official: string, reasonHash: string];
      export interface OutputObject {projectId: bigint, official: string, reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCancelledEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike];
      export type OutputTuple = [projectId: bigint, auditor: string];
      export interface OutputObject {projectId: bigint, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectClosedEvent {
      export type InputTuple = [projectId: BigNumberish, official: AddressLike];
      export type OutputTuple = [projectId: bigint, official: string];
      export interface OutputObject {projectId: bigint, official: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, official: AddressLike, wardId: BigNumberish, metaHash: BytesLike, metaCID: string, category: BigNumberish, departmentId: BigNumberish, latE6: BigNumberish, lngE6: BigNumberish, budget: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, contractor: AddressLike, approvalThreshold: BigNumberish];
      export type OutputTuple = [projectId: bigint, official: string, wardId: bigint, metaHash: string, metaCID: string, category: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, budget: bigint, startDate: bigint, endDate: bigint, contractor: string, approvalThreshold: bigint];
      export interface OutputObject {projectId: bigint, official: string, wardId: bigint, metaHash: string, metaCID: string, category: bigint, departmentId: bigint, latE6: bigint, lngE6: bigint, budget: bigint, startDate: bigint, endDate: bigint, contractor: string, approvalThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectPausedEvent {
      export type InputTuple = [projectId: BigNumberish, actor: AddressLike, reasonHash: BytesLike, grievanceId: BigNumberish];
      export type OutputTuple = [projectId: bigint, actor: string, reasonHash: string, grievanceId: bigint];
      export interface OutputObject {projectId: bigint, actor: string, reasonHash: string, grievanceId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectRejectedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike, reasonHash: BytesLike];
      export type OutputTuple = [projectId: bigint, auditor: string, reasonHash: string];
      export interface OutputObject {projectId: bigint, auditor: string, reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectResumedEvent {
      export type InputTuple = [projectId: BigNumberish, auditor: AddressLike];
      export type OutputTuple = [projectId: bigint, auditor: string];
      export interface OutputObject {projectId: bigint, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectStatusChangedEvent {
      export type InputTuple = [projectId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [projectId: bigint, status: bigint];
      export interface OutputObject {projectId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SpentUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, spent: BigNumberish];
      export type OutputTuple = [projectId: bigint, spent: bigint];
      export interface OutputObject {projectId: bigint, spent: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProjectRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProjectRegistry;
    waitForDeployment(): Promise<this>;

    interface: ProjectRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_APPROVAL_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    access: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    assignContractor: TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    closeProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmCancel: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProject: TypedContractMethod<
      [p: ProjectRegistry.NewProjectStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    escrow: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    exists: TypedContractMethod<
      [projectId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    getProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [IProjectRegistry.ProjectStructOutput],
      'view'
    >
    

    
    grievanceRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    hasApprovedProject: TypedContractMethod<
      [projectId: BigNumberish, auditor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [access_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    pauseByGrievance: TypedContractMethod<
      [projectId: BigNumberish, grievanceId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pauseProject: TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    projectCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordMilestoneCreated: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordSpent: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectProject: TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestCancel: TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    resumeProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setEscrow: TypedContractMethod<
      [escrow_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setGrievanceRegistry: TypedContractMethod<
      [grievance_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTenderRegistry: TypedContractMethod<
      [tender_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tenderRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_APPROVAL_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'access'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assignContractor'): TypedContractMethod<
      [projectId: BigNumberish, contractor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmCancel'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [p: ProjectRegistry.NewProjectStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrow'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [IProjectRegistry.ProjectStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grievanceRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasApprovedProject'): TypedContractMethod<
      [projectId: BigNumberish, auditor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [access_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseByGrievance'): TypedContractMethod<
      [projectId: BigNumberish, grievanceId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseProject'): TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'projectCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordMilestoneCreated'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordSpent'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectProject'): TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestCancel'): TypedContractMethod<
      [projectId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resumeProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEscrow'): TypedContractMethod<
      [escrow_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGrievanceRegistry'): TypedContractMethod<
      [grievance_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTenderRegistry'): TypedContractMethod<
      [tender_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tenderRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'ContractorAssigned'): TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'LinkedContractSet'): TypedContractEvent<LinkedContractSetEvent.InputTuple, LinkedContractSetEvent.OutputTuple, LinkedContractSetEvent.OutputObject>;
getEvent(key: 'MilestoneCountUpdated'): TypedContractEvent<MilestoneCountUpdatedEvent.InputTuple, MilestoneCountUpdatedEvent.OutputTuple, MilestoneCountUpdatedEvent.OutputObject>;
getEvent(key: 'ProjectApproved'): TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
getEvent(key: 'ProjectCancelRequested'): TypedContractEvent<ProjectCancelRequestedEvent.InputTuple, ProjectCancelRequestedEvent.OutputTuple, ProjectCancelRequestedEvent.OutputObject>;
getEvent(key: 'ProjectCancelled'): TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
getEvent(key: 'ProjectClosed'): TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'ProjectPaused'): TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
getEvent(key: 'ProjectRejected'): TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
getEvent(key: 'ProjectResumed'): TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
getEvent(key: 'ProjectStatusChanged'): TypedContractEvent<ProjectStatusChangedEvent.InputTuple, ProjectStatusChangedEvent.OutputTuple, ProjectStatusChangedEvent.OutputObject>;
getEvent(key: 'SpentUpdated'): TypedContractEvent<SpentUpdatedEvent.InputTuple, SpentUpdatedEvent.OutputTuple, SpentUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'ContractorAssigned(uint256,address,address)': TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
      ContractorAssigned: TypedContractEvent<ContractorAssignedEvent.InputTuple, ContractorAssignedEvent.OutputTuple, ContractorAssignedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'LinkedContractSet(bytes32,address)': TypedContractEvent<LinkedContractSetEvent.InputTuple, LinkedContractSetEvent.OutputTuple, LinkedContractSetEvent.OutputObject>;
      LinkedContractSet: TypedContractEvent<LinkedContractSetEvent.InputTuple, LinkedContractSetEvent.OutputTuple, LinkedContractSetEvent.OutputObject>;
    

      'MilestoneCountUpdated(uint256,uint16)': TypedContractEvent<MilestoneCountUpdatedEvent.InputTuple, MilestoneCountUpdatedEvent.OutputTuple, MilestoneCountUpdatedEvent.OutputObject>;
      MilestoneCountUpdated: TypedContractEvent<MilestoneCountUpdatedEvent.InputTuple, MilestoneCountUpdatedEvent.OutputTuple, MilestoneCountUpdatedEvent.OutputObject>;
    

      'ProjectApproved(uint256,address,uint8)': TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
      ProjectApproved: TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
    

      'ProjectCancelRequested(uint256,address,bytes32)': TypedContractEvent<ProjectCancelRequestedEvent.InputTuple, ProjectCancelRequestedEvent.OutputTuple, ProjectCancelRequestedEvent.OutputObject>;
      ProjectCancelRequested: TypedContractEvent<ProjectCancelRequestedEvent.InputTuple, ProjectCancelRequestedEvent.OutputTuple, ProjectCancelRequestedEvent.OutputObject>;
    

      'ProjectCancelled(uint256,address)': TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
      ProjectCancelled: TypedContractEvent<ProjectCancelledEvent.InputTuple, ProjectCancelledEvent.OutputTuple, ProjectCancelledEvent.OutputObject>;
    

      'ProjectClosed(uint256,address)': TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
      ProjectClosed: TypedContractEvent<ProjectClosedEvent.InputTuple, ProjectClosedEvent.OutputTuple, ProjectClosedEvent.OutputObject>;
    

      'ProjectCreated(uint256,address,uint32,bytes32,string,uint8,uint16,int32,int32,uint128,uint64,uint64,address,uint8)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'ProjectPaused(uint256,address,bytes32,uint256)': TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
      ProjectPaused: TypedContractEvent<ProjectPausedEvent.InputTuple, ProjectPausedEvent.OutputTuple, ProjectPausedEvent.OutputObject>;
    

      'ProjectRejected(uint256,address,bytes32)': TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
      ProjectRejected: TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
    

      'ProjectResumed(uint256,address)': TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
      ProjectResumed: TypedContractEvent<ProjectResumedEvent.InputTuple, ProjectResumedEvent.OutputTuple, ProjectResumedEvent.OutputObject>;
    

      'ProjectStatusChanged(uint256,uint8)': TypedContractEvent<ProjectStatusChangedEvent.InputTuple, ProjectStatusChangedEvent.OutputTuple, ProjectStatusChangedEvent.OutputObject>;
      ProjectStatusChanged: TypedContractEvent<ProjectStatusChangedEvent.InputTuple, ProjectStatusChangedEvent.OutputTuple, ProjectStatusChangedEvent.OutputObject>;
    

      'SpentUpdated(uint256,uint128)': TypedContractEvent<SpentUpdatedEvent.InputTuple, SpentUpdatedEvent.OutputTuple, SpentUpdatedEvent.OutputObject>;
      SpentUpdated: TypedContractEvent<SpentUpdatedEvent.InputTuple, SpentUpdatedEvent.OutputTuple, SpentUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }