/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TenderRegistry {
      
    export type BidStruct = {commitHash: BytesLike, amount: BigNumberish, revealedAt: BigNumberish, revealed: boolean}

    export type BidStructOutput = [commitHash: string, amount: bigint, revealedAt: bigint, revealed: boolean] & {commitHash: string, amount: bigint, revealedAt: bigint, revealed: boolean }
  

    export type TenderStruct = {id: BigNumberish, projectId: BigNumberish, commitDeadline: BigNumberish, revealDeadline: BigNumberish, winner: AddressLike, status: BigNumberish, bidCount: BigNumberish, revealedCount: BigNumberish, winningBid: BigNumberish}

    export type TenderStructOutput = [id: bigint, projectId: bigint, commitDeadline: bigint, revealDeadline: bigint, winner: string, status: bigint, bidCount: bigint, revealedCount: bigint, winningBid: bigint] & {id: bigint, projectId: bigint, commitDeadline: bigint, revealDeadline: bigint, winner: string, status: bigint, bidCount: bigint, revealedCount: bigint, winningBid: bigint }
  
    }

  export interface TenderRegistryInterface extends Interface {
    getFunction(nameOrSignature: "MAX_BIDDERS" | "UPGRADE_INTERFACE_VERSION" | "access" | "awardTender" | "cancelTender" | "commitBid" | "computeCommitment" | "getBid" | "getBidders" | "getTender" | "hasOpenTender" | "initialize" | "openTenderOf" | "proxiableUUID" | "publishTender" | "registry" | "revealBid" | "tenderCount" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BidCommitted" | "BidRevealed" | "Initialized" | "TenderAwarded" | "TenderCancelled" | "TenderPublished" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_BIDDERS', values?: undefined): string;
encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'access', values?: undefined): string;
encodeFunctionData(functionFragment: 'awardTender', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelTender', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'commitBid', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'computeCommitment', values: [BigNumberish, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getBid', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getBidders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTender', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasOpenTender', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'openTenderOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishTender', values: [BigNumberish, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'revealBid', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'tenderCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_BIDDERS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'access', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'awardTender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeCommitment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBidders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasOpenTender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openTenderOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishTender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenderCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace BidCommittedEvent {
      export type InputTuple = [tenderId: BigNumberish, bidder: AddressLike, commitHash: BytesLike];
      export type OutputTuple = [tenderId: bigint, bidder: string, commitHash: string];
      export interface OutputObject {tenderId: bigint, bidder: string, commitHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidRevealedEvent {
      export type InputTuple = [tenderId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tenderId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {tenderId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TenderAwardedEvent {
      export type InputTuple = [tenderId: BigNumberish, projectId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tenderId: bigint, projectId: bigint, winner: string, amount: bigint];
      export interface OutputObject {tenderId: bigint, projectId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TenderCancelledEvent {
      export type InputTuple = [tenderId: BigNumberish, projectId: BigNumberish, reasonHash: BytesLike];
      export type OutputTuple = [tenderId: bigint, projectId: bigint, reasonHash: string];
      export interface OutputObject {tenderId: bigint, projectId: bigint, reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TenderPublishedEvent {
      export type InputTuple = [tenderId: BigNumberish, projectId: BigNumberish, official: AddressLike, metaCID: string, commitDeadline: BigNumberish, revealDeadline: BigNumberish];
      export type OutputTuple = [tenderId: bigint, projectId: bigint, official: string, metaCID: string, commitDeadline: bigint, revealDeadline: bigint];
      export interface OutputObject {tenderId: bigint, projectId: bigint, official: string, metaCID: string, commitDeadline: bigint, revealDeadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TenderRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): TenderRegistry;
    waitForDeployment(): Promise<this>;

    interface: TenderRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_BIDDERS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    access: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    awardTender: TypedContractMethod<
      [tenderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTender: TypedContractMethod<
      [tenderId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    commitBid: TypedContractMethod<
      [tenderId: BigNumberish, commitHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    computeCommitment: TypedContractMethod<
      [tenderId: BigNumberish, bidder: AddressLike, amount: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    getBid: TypedContractMethod<
      [tenderId: BigNumberish, bidder: AddressLike, ],
      [TenderRegistry.BidStructOutput],
      'view'
    >
    

    
    getBidders: TypedContractMethod<
      [tenderId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getTender: TypedContractMethod<
      [tenderId: BigNumberish, ],
      [TenderRegistry.TenderStructOutput],
      'view'
    >
    

    
    hasOpenTender: TypedContractMethod<
      [projectId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    openTenderOf: TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publishTender: TypedContractMethod<
      [projectId: BigNumberish, metaCID: string, commitDeadline: BigNumberish, revealDeadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revealBid: TypedContractMethod<
      [tenderId: BigNumberish, amount: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    tenderCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_BIDDERS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'access'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'awardTender'): TypedContractMethod<
      [tenderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTender'): TypedContractMethod<
      [tenderId: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitBid'): TypedContractMethod<
      [tenderId: BigNumberish, commitHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'computeCommitment'): TypedContractMethod<
      [tenderId: BigNumberish, bidder: AddressLike, amount: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBid'): TypedContractMethod<
      [tenderId: BigNumberish, bidder: AddressLike, ],
      [TenderRegistry.BidStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getBidders'): TypedContractMethod<
      [tenderId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTender'): TypedContractMethod<
      [tenderId: BigNumberish, ],
      [TenderRegistry.TenderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasOpenTender'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [access_: AddressLike, registry_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openTenderOf'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishTender'): TypedContractMethod<
      [projectId: BigNumberish, metaCID: string, commitDeadline: BigNumberish, revealDeadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revealBid'): TypedContractMethod<
      [tenderId: BigNumberish, amount: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tenderCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'BidCommitted'): TypedContractEvent<BidCommittedEvent.InputTuple, BidCommittedEvent.OutputTuple, BidCommittedEvent.OutputObject>;
getEvent(key: 'BidRevealed'): TypedContractEvent<BidRevealedEvent.InputTuple, BidRevealedEvent.OutputTuple, BidRevealedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'TenderAwarded'): TypedContractEvent<TenderAwardedEvent.InputTuple, TenderAwardedEvent.OutputTuple, TenderAwardedEvent.OutputObject>;
getEvent(key: 'TenderCancelled'): TypedContractEvent<TenderCancelledEvent.InputTuple, TenderCancelledEvent.OutputTuple, TenderCancelledEvent.OutputObject>;
getEvent(key: 'TenderPublished'): TypedContractEvent<TenderPublishedEvent.InputTuple, TenderPublishedEvent.OutputTuple, TenderPublishedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'BidCommitted(uint256,address,bytes32)': TypedContractEvent<BidCommittedEvent.InputTuple, BidCommittedEvent.OutputTuple, BidCommittedEvent.OutputObject>;
      BidCommitted: TypedContractEvent<BidCommittedEvent.InputTuple, BidCommittedEvent.OutputTuple, BidCommittedEvent.OutputObject>;
    

      'BidRevealed(uint256,address,uint256)': TypedContractEvent<BidRevealedEvent.InputTuple, BidRevealedEvent.OutputTuple, BidRevealedEvent.OutputObject>;
      BidRevealed: TypedContractEvent<BidRevealedEvent.InputTuple, BidRevealedEvent.OutputTuple, BidRevealedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'TenderAwarded(uint256,uint256,address,uint256)': TypedContractEvent<TenderAwardedEvent.InputTuple, TenderAwardedEvent.OutputTuple, TenderAwardedEvent.OutputObject>;
      TenderAwarded: TypedContractEvent<TenderAwardedEvent.InputTuple, TenderAwardedEvent.OutputTuple, TenderAwardedEvent.OutputObject>;
    

      'TenderCancelled(uint256,uint256,bytes32)': TypedContractEvent<TenderCancelledEvent.InputTuple, TenderCancelledEvent.OutputTuple, TenderCancelledEvent.OutputObject>;
      TenderCancelled: TypedContractEvent<TenderCancelledEvent.InputTuple, TenderCancelledEvent.OutputTuple, TenderCancelledEvent.OutputObject>;
    

      'TenderPublished(uint256,uint256,address,string,uint64,uint64)': TypedContractEvent<TenderPublishedEvent.InputTuple, TenderPublishedEvent.OutputTuple, TenderPublishedEvent.OutputObject>;
      TenderPublished: TypedContractEvent<TenderPublishedEvent.InputTuple, TenderPublishedEvent.OutputTuple, TenderPublishedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }