/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITenderRegistry, ITenderRegistryInterface } from "../../interfaces/ITenderRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      }
    ],
    "name": "hasOpenTender",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITenderRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): ITenderRegistryInterface {
      return new Interface(_abi) as ITenderRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITenderRegistry {
      return new Contract(address, _abi, runner) as unknown as ITenderRegistry;
    }
  }
  